### PR TITLE
make hashes more readable and use real constant names

### PR DESCRIPTION
**Pull request by grosser**
@doches

### CODE REVIEW

**Comment by doches** [comment]
What's the motivation for this change? Preference for C-style constants (`HYPERNYM`) over minimal Ruby constants (`Hypernym`) seems like just that -- a preference. This feels like changing things for the sake of changing things. Aside from the whitespace formatting around the pointer maps, which is a worthwhile change.

This will break existing code (e.g. `synsets[0].get_relation(WordNet::Hypernym)`) for *very* little gain.

**Comment by grosser** [comment]
I'm just going through the files 1-by-1 and fix whatever looks
outdated/wrong
for constants I like to follow the ruby style guide / every other ruby
program I have seen so far -
https://github.com/bbatsov/ruby-style-guide#syntax

classes are CamelCase, methods are snake_case, constants are UPPER_CASE

**Comment by doches** [comment]
Yeah, I get that Ruby has settled on FULL_CASE constant names, but updating this is an *API-breaking* change. This combined with #13 is sufficiently breaking to motivate me to call this rwordnet2, except that there wouldn't really be any benefit to users to upgrade to it then (a la AngularJS2.0).

**Comment by grosser** [comment]
I don't think there is a reason to change the gem name, just major bump it
once everything is done. There have been more breaking changes in minor
version bumps in many gems :)

**Comment by grosser** [comment]
also it's not like this is rails/rake, this is a very special purpose library installed 7k times since 2010, so not that many users to complain/be disturbed anyway :)

**Comment by doches** [comment]
:)

Sensible --  finish your style overhaul and I'll bump the major version when you're done. The bugfixes alone are probably worth it anyway.

**Pull request merged**
