### PR TITLE
kill index, make lemma find things, cache nils, make db responsible for ...

### PR DESCRIPTION
**Pull request by grosser**
...opening+location

 - index was generally pretty useless and the singleton was annoying
 - Lemma.find/find_all makes more sense to me (maybe AR overdose ...)
 - DB should be responsible for opening and not be told what the path is
 - also caching nil now
 - caching by search word and not by lemma.word (otherwise caching would miss)
 - db auto-closes itself, no longer manages file handles

@doches 

best viewed without whitespace [w=1](https://github.com/doches/rwordnet/pull/15/files?w=1)

### CODE REVIEW

**Comment by grosser** [comment]
- kicking out get_synsets
 - fixing bug where `"."` would find the first lemma since it was interpolated as regexp

**Comment by grosser** [comment]
atm we rescan the db file multiple times / for every missing word, a better approach might be to just load that whole thing into cache and not try to re-parse it on every failed lookup ?

alternatively store the offset we already looked up to

and a no-cache mode would be nice for usecase where I don't want to load everything into the cache

**Comment by grosser** [comment]
benchmark:
```
before (partial scan / bad caching):
Time to initial word 0.184821
Time for 1k lookups 0.006725

after (full scan):
Time to initial word 0.169815
Time for 1k lookups 0.006055
```

will now also produce far less garbage and take up less memory

**Comment by grosser** [comment]
@doches is this good to go ?

**Comment by doches** [comment]
Sticking that functionality into Lemma rather than the singleton is something I've meant to do for ages. Sweet.

**Pull request merged**
