### PR TITLE
pos is empty

### PR DESCRIPTION
**Pull request by grosser**
@doches

### CODE REVIEW

**Comment by grosser** [comment]
@doches can you review these PRs, I want to make 1 more change but not keep piling onto these

**Comment by grosser** [comment]
@doches ping

**Comment by grosser** [comment]
@doches pong

**Comment by grosser** [comment]
@doches ping

**Comment by grosser** [comment]
@doches

**Comment by doches** [comment]
Yo, sorry -- been travelling for the last week or so. Bleurgh.

This is obviously a good PR; what the hell was that doing in there in the first place?

**Pull request merged**
