### PR TITLE
streamline the readme

### PR DESCRIPTION
**Pull request by grosser**
@doches 

trying to get the facts out front and center + some size stats (another good reason to pick it since heroku only allows 100mb total for all gems) :)

[rendered](https://github.com/grosser/rwordnet/blob/grosser/readme/README.markdown)

### CODE REVIEW

**Comment by grosser** [comment]
@doches is this good to go ?

**Comment by doches** [comment]
Nope. While I respect what you're trying to do with the README, you've edited all of the personality right out. I'd rather hang on to the existing README and add in a few of the salient points you've made (highlighting no dependencies, smaller file size, & the like).

Which I shall go off and do now, actually. Because you're totally right in that I ought to call those good things out up front.

**Comment by grosser** [comment]
What do you do when you see a wordy readme like that on a different
project, do you actually read it all ? or do you scan it to get the key
facts ?
I always scan it / do not care for wordy/personality/blah-blah, I got x
gems to choose from and the first one that convinces me wins :)

**Comment by grosser** [comment]
basically what I see when opening the page is this:

screencapture-github-com-doches-rwordnet

**Comment by doches** [comment]
I read it.

That's fine -- you're free to scan for code samples when picking libraries. I prefer to have a little more information (including, among other things, how likely I am to get support from the author -- something that's rarely specified but pretty easy to glean from the tone of the README).

Text/no text is a cost/benefit trade-off for me. People who don't want it pay a small cost when they have to read it, but people who care about docs pay a large cost when they're missing. Basically: you can skim over text, but if it ain't there it ain't there.

**Comment by grosser** [comment]
idk if there is a correlation between nice 'tone' readme and maintenance
status ...

I'm also not suggesting to leave out information, just making the
information more visible by reducing the chatter.
How about, as a middle ground, to having the bullet-points out front and
then diving into the chit-chat ?

**Comment by doches** [comment]
Reasonable. I'll make that change (I'm perhaps overly-protective of the README, which you may have figured out by now).

**Comment by grosser** [comment]
Hehe :D

**Pull request closed without merging**
